"""password_hash

Revision ID: 811d5f4d5ada
Revises: 513854416fad
Create Date: 2024-04-24 16:25:21.114709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811d5f4d5ada'
down_revision = '513854416fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
